In [1]:
import pandas as pd
people = {
    "first": ["Corney", "Jane", "Dima"], 
    "second": ["Spiler", "Doe", "Markow"], 
    "email" : ["ssd@", "sdfd@", "gbbhn@"]
}
df = pd.DataFrame(people)
df

    first  second   email
0  Corney  Spiler    ssd@
1    Jane     Doe   sdfd@
2    Dima  Markow  gbbhn@

In [2]:
df.loc[[1, 2], "second"]

1       Doe
2    Markow
Name: second, dtype: object

In [3]:
df.columns

Index(['first', 'second', 'email'], dtype='object')

In [4]:
df.columns = ['first_name', 'second_name', 'email']
df

  first_name second_name   email
0     Corney      Spiler    ssd@
1       Jane         Doe   sdfd@
2       Dima      Markow  gbbhn@

In [5]:
df.columns = [col.upper() for col in df.columns]
df

  FIRST_NAME SECOND_NAME   EMAIL
0     Corney      Spiler    ssd@
1       Jane         Doe   sdfd@
2       Dima      Markow  gbbhn@

In [6]:
df.columns = df.columns.str.replace('_', '-')
df

  FIRST-NAME SECOND-NAME   EMAIL
0     Corney      Spiler    ssd@
1       Jane         Doe   sdfd@
2       Dima      Markow  gbbhn@

In [7]:
df.columns = [col.lower() for col in df.columns]
df

  first-name second-name   email
0     Corney      Spiler    ssd@
1       Jane         Doe   sdfd@
2       Dima      Markow  gbbhn@

In [8]:
df.rename(columns={'first-name': 'first', 'second-name':'last'}, inplace=True)
df

    first    last   email
0  Corney  Spiler    ssd@
1    Jane     Doe   sdfd@
2    Dima  Markow  gbbhn@

# Updating date in the DF

In [9]:
df.loc[2, 'email'] = 'dima@gmail.com'
df

    first    last           email
0  Corney  Spiler            ssd@
1    Jane     Doe           sdfd@
2    Dima  Markow  dima@gmail.com

In [10]:
df.loc[0] = ['Adriana', 'G', 'adrG@gmalcom']
df

     first    last           email
0  Adriana       G    adrG@gmalcom
1     Jane     Doe           sdfd@
2     Dima  Markow  dima@gmail.com

In [11]:
df.loc[1, ['last', 'email']] = ['Lans', 'jlans@gmail.com'] #or df.loc[filt_fuctions, 'name_of_col'] = ...
df

     first    last            email
0  Adriana       G     adrG@gmalcom
1     Jane    Lans  jlans@gmail.com
2     Dima  Markow   dima@gmail.com

In [12]:
df.at[1, 'last'] = 'Green' #probably faster then loc
df

     first    last            email
0  Adriana       G     adrG@gmalcom
1     Jane   Green  jlans@gmail.com
2     Dima  Markow   dima@gmail.com

# Updating date columns

In [13]:
df['email'] = df['email'].str.lower()
df

     first    last            email
0  Adriana       G     adrg@gmalcom
1     Jane   Green  jlans@gmail.com
2     Dima  Markow   dima@gmail.com

## apply(func) -> used for each row

#### with Series

In [14]:
df['email'].apply(len)

0    12
1    15
2    14
Name: email, dtype: int64

In [16]:
df = df['email'].apply(lambda email : email.upper())

     first    last            email
0  Adriana       G     adrg@gmalcom
1     Jane   Green  jlans@gmail.com
2     Dima  Markow   dima@gmail.com

In [17]:
df['email'] = df['email'].str.lower()
df

     first    last            email
0  Adriana       G     adrg@gmalcom
1     Jane   Green  jlans@gmail.com
2     Dima  Markow   dima@gmail.com

#### with DataFrames

In [18]:
df.apply(len) #used for each column by default

first    3
last     3
email    3
dtype: int64

In [20]:
df.apply(len, axis='columns') #used for each row

0    3
1    3
2    3
dtype: int64

In [21]:
df.apply(pd.Series.min)

first         Adriana
last                G
email    adrg@gmalcom
dtype: object

## DataFrame.map(func) -> applies func for each element in DataFrame

In [23]:
df.map(len)

   first  last  email
0      7     1     12
1      4     5     15
2      4     6     14

In [ ]:
## DataFrame.map(func) -> applies func for each element in DataFrame